In [1]:
import torch
x = torch.empty(3,5)
print(x)

tensor([[1.3335e-18, 8.3517e-43, 1.3335e-18, 8.3517e-43, 1.3334e-18],
        [8.3517e-43, 1.3334e-18, 8.3517e-43, 1.3336e-18, 8.3517e-43],
        [1.3336e-18, 8.3517e-43, 1.3334e-18, 8.3517e-43, 1.3334e-18]])


In [3]:
x = torch.rand(5,3)
x

tensor([[0.4555, 0.8133, 0.5703],
        [0.9362, 0.4168, 0.3849],
        [0.5601, 0.1689, 0.8770],
        [0.7200, 0.5558, 0.7310],
        [0.1653, 0.0448, 0.3783]])

In [6]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x = torch.tensor([3,5])
x

tensor([3, 5])

In [15]:
x = x.new_ones(5,3,dtype=torch.float)
x = torch.rand_like(x,dtype=torch.float)
x.size()

torch.Size([5, 3])

In [16]:
y = torch.rand(5,3)

In [17]:
x+y

tensor([[1.1029, 1.6848, 0.8526],
        [1.5698, 1.7625, 0.8882],
        [0.9760, 1.2432, 0.7506],
        [0.2308, 0.8041, 1.1747],
        [1.5599, 0.5384, 1.4706]])

In [18]:
x[:1]

tensor([[0.2241, 0.9502, 0.7774]])

In [20]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.shape,y.shape,z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [25]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
#both changed since they share memory location
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
if (torch.cuda.is_available()):
    device = torch.device('cuda')
    y = torch.ones_like(x,device = device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to('cpu',torch.double))

tensor([[1.2763, 1.5595, 1.1164, 1.9013],
        [1.7677, 1.3642, 1.4237, 1.7190],
        [1.3000, 1.4236, 1.1297, 1.5297],
        [1.6520, 1.3740, 1.6704, 1.5152]], device='cuda:0')
tensor([[1.2763, 1.5595, 1.1164, 1.9013],
        [1.7677, 1.3642, 1.4237, 1.7190],
        [1.3000, 1.4236, 1.1297, 1.5297],
        [1.6520, 1.3740, 1.6704, 1.5152]], dtype=torch.float64)


In [28]:
torch.cuda.is_available()

True