In [4]:
import torch
x = torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
y.grad_fn

In [8]:
z = y*y*3
z
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [9]:
a = torch.ones(2,2)
a = a*3/(a-1)
a.requires_grad

False

In [10]:
a.requires_grad_(True)

tensor([[inf, inf],
        [inf, inf]], requires_grad=True)

In [12]:
out.backward(torch.tensor(1.))

In [13]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [17]:
x = torch.rand(3,requires_grad=True)
y = x*2
print(y)
while y.data.norm() < 1000:
    y *= 2
print(y)    

tensor([1.8647, 0.2410, 0.4447], grad_fn=<MulBackward0>)
tensor([1909.4160,  246.7546,  455.4080], grad_fn=<MulBackward0>)


In [18]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [22]:
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
False


In [23]:
y = x.detach()
print(y.requires_grad)

False
