In [1]:
import torch

In [2]:
lst = list(range(9))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
ls = torch.tensor(lst)
ls

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
l = ls[1]
print(ls.shape)
print(ls.storage_offset())
print(ls.stride())

torch.Size([9])
0
(1,)


In [5]:
b = ls.view(3,3) # reshape
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
c = b[1:,1:]

In [7]:
print(c.shape)
print(c.storage_offset())
print(c.stride())

torch.Size([2, 2])
4
(3, 1)


In [8]:
c

tensor([[4, 5],
        [7, 8]])

In [9]:
torch.cos(c.float())

tensor([[-0.6536,  0.2837],
        [ 0.7539, -0.1455]])